name: geo-bin
version: master
summary: ls, cp, mkdir, mirror commands for filesystems and object storage.
description: |
  Geo provides a modern alternative to UNIX commands
  like ls, cat, cp, mirror, diff etc. It supports filesystems and
  Amazon S3 compatible cloud storage service (AWS Signature v2 and v4).

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode

apps:
apps:
  geo-bin:
    command: geo
    plugs:
      - home
      - mount-observe
      - network
      - network-bind
      - removable-media
    aliases: [geo]
parts:
  geo:
    source: .
    plugin: nil
    build-packages: [make,]
    override-build: |     
      mkdir -p ../go/src/github.com/piensa/geo
      cp -R . ../go/src/github.com/piensa/geo
      env GOPATH=$(pwd)/../go GOARCH=$TARGET_GOARCH make -C ../go/src/github.com/piensa/geo install
      snapcraftctl build
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      mv ../go/bin/geo $SNAPCRAFT_PART_INSTALL/bin/
    after: [go]
  go:
    source-tag: go1.10.3
