name: gnd
version: master
summary: ls, cp, mkdir, mirror commands for filesystems and object storage.
description: |
  Geo provides a modern alternative to UNIX commands
  like ls, cat, cp, mirror, diff etc. It supports filesystems and
  Amazon S3 compatible cloud storage service (AWS Signature v2 and v4).

grade: stable
confinement: strict

apps:
  gnd:
    command: gnd
    plugs:
      - home
      - mount-observe
      - network
      - removable-media
parts:
  gnd:
    source: .
    plugin: nil
    build-packages: [make,]
    override-build: |     
      mkdir -p ../go/src/github.com/piensa/gnd
      cp -R . ../go/src/github.com/piensa/gnd
      env GOPATH=$(pwd)/../go make -C ../go/src/github.com/piensa/gnd install
      snapcraftctl build
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      mv ../go/bin/gnd $SNAPCRAFT_PART_INSTALL/bin/
    after: [go]
  go:
    source-tag: go1.10.3
